# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
latex: false
cache: 
  packages: yes
  directories:
    - $HOME/bin
    - $HOME/.TinyTeX

script:
- Rscript -e 'if (tinytex::tinytex_root() == "") tinytex::install_tinytex()'
- Rscript -e 'tinytex::tlmgr_install("cm-super")'
- Rscript -e 'dir.create("manuscript/dist")'
- Rscript -e 'rmarkdown::render("manuscript/manuscript.Rmd", output_dir = "manuscript/dist/")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: manuscript/dist
